corpus:
  name: 'CMU_ARCTIC' # unused info
  path: '/home/beiming/data/cmu_arctic'                

experimental_setup:
  model_type: 'VC'                   
  experiment_type: 'one-to-one' # unused info

data_setup:
  source_spk_list: ['aew', 'ahw']  # ['aew', 'ahw', 'aup', 'awb', 'axb', 'bdl', 'clb', 'eey', 'fem', 'gka', 'jmk', 'ksp', 'ljm', 'lnh', 'rms', 'rxr', 'slp', 'slt']
  target_spk_list: ['aew', 'ahw']  # Will perform cross validation, and skip the same speakers

acoustic_feature:
  sampling_rate: 22050 
  filter_length: 1024 
  hop_length: 256 
  win_length: 1024 
  n_mel_channels: 80 
  mel_fmin: 0.0 
  mel_fmax: 8000.0

training_setup:
  normalization:
    input: True
    output: True
  train_val_test_ratio: [0.8, 0.1, 0.1] # train ratio, valid ratio, test_ratio

NN: 'LSTM' # DNN, LSTM, BLSTM
NN_setup:
  hidden_size: 256
  layer_num: 3
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.000
  num_epoch: 50

testing_setup:
  save_model: True
  save_output: True
  synthesis_samples: True
